version: 2.1
jobs:
  print-my-name:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Print my name"
          command: 
            echo $MY_ENV_VAR

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  print-name-workflow:
    jobs:
      - print-my-name
